const houseData = [
  {
    id: 1,
    location: "Nyarugenge",
    status:"unrented",
    price: 70000,
    size: 2000,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.beautiful house in Nyarugenge",
    image: "/Images/houseImages/mainImage1.jpeg",
    link: "/houses",
    numberOfBeds:2,

    images: [
      "/Images/houseImages/mainImage1.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 2,
    location: "Kicukiro",
    status:"pending",
    price: 46000,
    size: 1800,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage2.jpeg",
    link: "/houses",
    numberOfBeds:1,


    images: [
      "/Images/houseImages/mainImage2.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house9.jpeg",
    ],
  },
  {
    id: 3,
    location: "Gasabo",
    status:"rented",
    price: 50000,
    size: 1500,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage3.jpeg",
    link: "/houses",
    numberOfBeds:2,


    images: [
      "/Images/houseImages/mainImage3.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
    ],
  },
  {
    id: 4,
    location: "Nyarugenge",
    status:"unrented",
    price: 15000,
    size: 2500,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage4.jpeg",
    link: "/houses",
    numberOfBeds:1,


    images: [
      "/Images/houseImages/mainImage4.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 5,
    location: "Kicukiro",
    status:"rented",
    price: 33000,
    size: 2000,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",

    image: "/Images/houseImages/mainImage10.jpg",
    link: "/houses",
    numberOfBeds:1,


    images: [
      "/Images/houseImages/mainImage10.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/mainImage1.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
    ],
  },
  {
    id: 6,
    location: "Gasabo",
    status:"rented",
    price: 40000,
    size: 1700,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",

    image: "/Images/houseImages/mainImage11.jpg",
    link: "/houses",
    numberOfBeds:1,


    images: [
      "/Images/houseImages/mainImage11.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 7,
    location: "Nyarugenge",
    status:"unrented",
    price: 48000,
    size: 1900,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",

    image: "/Images/houseImages/mainImage12.jpg",
    link: "/houses",
    numberOfBeds:3,


    images: [
      "/Images/houseImages/mainImage12.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 8,
    location: "Kicukiro",
    status:"unrented",
    price: 100000,
    size: 1600,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",

    image: "/Images/houseImages/mainImage13.jpg",
    link: "/houses",
    numberOfBeds:3,


    images: [
      "/Images/houseImages/mainImage13.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 9,
    location: "Gasabo",
    status:"unrented",
    price: 150000,
    size: 1400,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage14.jpg",
    link: "/houses",
    numberOfBeds:6,


    images: [
      "/Images/houseImages/mainImage14.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 10,
    location: "Nyarugenge",
    status:"unrented",
    price: 60000,
    size: 2100,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage15.jpg",
    link: "/houses",
    numberOfBeds:2,


    images: [
      "/Images/houseImages/mainImage15.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 11,
    location: "Kicukiro",
    status:"rented",
    price: 80000,
    size: 1800,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage16.jpg",
    link: "/houses",
    numberOfBeds:3,


    images: [
      "/Images/houseImages/mainImage16.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 12,
    location: "Gasabo",
    status:"pending",
    price: 90000,
    size: 1500,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage17.jpg",
    link: "/houses",
    numberOfBeds:3,


    images: [
      "/Images/houseImages/mainImage17.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 13,
    location: "Nyarugenge",
    status:"unrented",
    price: 75000,
    size: 2600,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage18.jpg",
    link: "/houses",
    numberOfBeds:2,


    images: [
      "/Images/houseImages/mainImage18.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 14,
    location: "Kicukiro",
    status:"rented",
    price: 25000,
    size: 1900,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",

    image: "/Images/houseImages/mainImage19.jpg",
    link: "/houses",
    numberOfBeds:3,


    images: [
      "/Images/houseImages/mainImage19.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 15,
    location: "Gasabo",
    status:"pending",
    price: 42000,
    size: 1600,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",

    image: "/Images/houseImages/mainImage20.jpg",
    link: "/houses",
    numberOfBeds:1,


    images: [
      "/Images/houseImages/mainImage20.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 16,
    location: "Nyarugenge",
    status:"unrented",
    price: 85000,
    size: 2000,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",

    image: "/Images/houseImages/mainImage10.jpg",
    link: "/houses",
    numberOfBeds:1,


    images: [
      "/Images/houseImages/mainImage10.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 17,
    location: "Kicukiro",
    status:"rented",
    price: 160000,
    size: 1700,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",

    image: "/Images/houseImages/mainImage11.jpg",
    link: "/houses",
    numberOfBeds:3,


    images: [
      "/Images/houseImages/mainImage11.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 18,
    location: "Gasabo",
    status:"pending",
    price: 13300,
    size: 1400,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage12.jpg",
    link: "/houses",
    numberOfBeds:4,


    images: [
      "/Images/houseImages/mainImage12.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
    ],
  },
  {
    id: 19,
    location: "Nyarugenge",
    status:"unrented",
    price: 16200,
    size: 2200,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage14.jpg",
    link: "/houses",
    numberOfBeds:1,


    images: [
      "/Images/houseImages/mainImage14.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
  {
    id: 20,
    location: "Kicukiro",
    status:"rented",
    price: 46000,
    size: 1800,
    description:
      "This charming 3-bedroom, 2-bathroom home offers a spacious open floor plan with a modern kitchen, featuring stainless steel appliances and granite countertops.",
    image: "/Images/houseImages/mainImage15.jpg",
    link: "/houses",
    numberOfBeds:3,


    images: [
      "/Images/houseImages/mainImage15.jpg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house10.jpeg",
      "/Images/houseImages/house11.jpeg",
      "/Images/houseImages/house12.jpeg",
      "/Images/houseImages/house13.jpeg",
      "/Images/houseImages/house14.jpeg",
      "/Images/houseImages/house15.jpeg",
      "/Images/houseImages/house16.jpeg",
      "/Images/houseImages/house17.jpeg",
      "/Images/houseImages/house18.jpeg",
      "/Images/houseImages/house8.jpeg",
    ],
  },
];

export default houseData;
