const houseData = [
  {
    id: 1,
    location: "New York",
    price: 5000,
    size: 2000,
    description: "A beautiful house in New York",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 2,
    location: "Los Angeles",
    price: 4500,
    size: 1800,
    description: "A lovely house in Los Angeles",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 3,
    location: "Chicago",
    price: 3000,
    size: 1500,
    description: "A cozy house in Chicago",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 4,
    location: "New York",
    price: 7000,
    size: 2500,
    description: "Luxury house in New York",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 5,
    location: "Los Angeles",
    price: 5200,
    size: 2000,
    description: "Spacious house in Los Angeles",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 6,
    location: "Chicago",
    price: 4000,
    size: 1700,
    description: "Modern house in Chicago",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 7,
    location: "New York",
    price: 4800,
    size: 1900,
    description: "Stylish house in New York",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 8,
    location: "Los Angeles",
    price: 4300,
    size: 1600,
    description: "Charming house in Los Angeles",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 9,
    location: "Chicago",
    price: 3100,
    size: 1400,
    description: "Elegant house in Chicago",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 10,
    location: "New York",
    price: 6000,
    size: 2100,
    description: "Beautiful house in New York",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 11,
    location: "Los Angeles",
    price: 4700,
    size: 1800,
    description: "Lovely house in Los Angeles",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 12,
    location: "Chicago",
    price: 3200,
    size: 1500,
    description: "Cozy house in Chicago",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 13,
    location: "New York",
    price: 7500,
    size: 2600,
    description: "Luxury house in New York",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 14,
    location: "Los Angeles",
    price: 5100,
    size: 1900,
    description: "Spacious house in Los Angeles",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 15,
    location: "Chicago",
    price: 4200,
    size: 1600,
    description: "Modern house in Chicago",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 16,
    location: "New York",
    price: 4900,
    size: 2000,
    description: "Stylish house in New York",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 17,
    location: "Los Angeles",
    price: 4400,
    size: 1700,
    description: "Charming house in Los Angeles",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 18,
    location: "Chicago",
    price: 3300,
    size: 1400,
    description: "Elegant house in Chicago",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 19,
    location: "New York",
    price: 6200,
    size: 2200,
    description: "Beautiful house in New York",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
  {
    id: 20,
    location: "Los Angeles",
    price: 4600,
    size: 1800,
    description: "Lovely house in Los Angeles",
    image: "/Images/houseImages/house1.jpeg",
    link: "/houses",
  },
];

export default houseData;
